### ISSUE TITLE
[add-resource] A vue.js example plugin

### ISSUE THREAD

**Issue by ash0080** [getgrav/awesome-grav#8]
I'd like to add my vue.js example plugin to this Repository.
The plugin inject a <div> entry point into the page.content automatically. so, it's need install and ready to run.

more details here: [grav-plugin-vue-example](https://github.com/ash0080/grav-plugin-vue-example)

**Comment by OleVik** [comment]
You should flesh out the README for the plugin, to illustrate how to use it. As is, its unclear how its implemented in a theme.

**Comment by ash0080** [comment]
it's out of box， don't need do anything in the theme

**Comment by w00fz** [comment]
I like this! 👍

**Comment by rhukster** [comment]
Added to GPM for next release

**Comment by rhukster** [comment]
You need to add this via the main Grav Issues list: github.com/getgrav/grav/issues

**Comment by ash0080** [comment]
@rhukster  May I ?  Cuz it's only an example plugin,  i'm kinda shy 😈

**Comment by w00fz** [comment]
I think Andy might have confused the repository due to the way you titled this issue.

I added your plugin example in the list https://github.com/getgrav/awesome-grav/commit/db1f2498a185557aa3a3cd5137e15ed37403d685

Thanks!

**Comment by rhukster** [comment]
I misunderstood, i thought you were asking for this to be added to GPM, and was just in the wrong place.
